-- Run this script in your Supabase SQL Editor (Dashboard > SQL Editor > New Query)

-- 1. Create the 'logins' table
CREATE TABLE IF NOT EXISTS public.logins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (optional but recommended for production)
-- For this demo, we'll allow all inserts from the web client
ALTER TABLE public.logins ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow anyone to insert (since it's a login form)
CREATE POLICY "Allow public insert" ON public.logins
FOR INSERT WITH CHECK (true);

-- 4. Create a policy to allow only the service role or yourself to read (protecting user data)
CREATE POLICY "Allow authenticated read" ON public.logins
FOR SELECT USING (auth.role() = 'service_role');
